version: "2.4"
services:
  rocketwatch:
    image: invisiblesymbol/rocketwatch
    volumes:
      - ./rocketwatch/contracts/rocketpool:/app/contracts/rocketpool
      - ./rocketwatch/main.cfg:/app/main.cfg
    restart: unless-stopped
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    # required to access my node containers
    networks:
      - ethereum
    labels:
      com.centurylinklabs.watchtower.enable: true

  mongodb:
    image: mongo:6.0.5
    volumes:
      - ./mongodb:/data/db
    restart: unless-stopped
    # bellow prevents unecessary data from being colleted
    command: --setParameter diagnosticDataCollectionEnabled=false
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    networks:
      - ethereum
    ports:
      - "127.0.0.1:27017:27017"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
      --label-enable

networks:
  ethereum:
    name: ethereum
